# Site settings
title: Electronut Labs
email: info@electronut.in
description: > # this means to ignore newlines until "baseurl:"
  Electronut Labs is a blog on Programming and Embedded Systems.

#url:              http://localhost:4000
url:              http://electronut.in

baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site

twitter_username: electronutLabs
github_username:  electronut

# Build settings
markdown: kramdown

permalink:   /:title/

gems: 
  - jekyll-paginate
  - jekyll-archives

paginate: 10
paginate_path: "blog/page:num"